# Generated by Django 3.1.1 on 2020-09-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('publishedAt', models.CharField(max_length=20)),
                ('channelTitle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_type', models.CharField(choices=[('DE', 'default'), ('ME', 'medium'), ('HI', 'high')], max_length=2)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('url', models.URLField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='YoutubeSearch.videodata')),
            ],
        ),
    ]
