# Generated by Django 3.1.1 on 2020-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='publishedAt',
            field=models.DateTimeField(),
        ),
    ]
