# Generated by Django 3.1.1 on 2020-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSearch', '0004_auto_20200928_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='publishedAt',
            field=models.DateTimeField(),
        ),
    ]
